### ISSUE TITLE
measurement.result not working for final measurements when intermediate measurements are present

### ISSUE THREAD

**Issue by Simone-Bordoni** [qiboteam/qibo#1094]
When executing a circuit with intermediate measurements it is not possible to get the final measurement results directly from the measurement gate

```python
from qibo import gates
from qibo.models import Circuit
measurement = gates.M(0)
measurement2 = gates.M(0,1,2)

circ = Circuit(3, density_matrix=True)
circ.add(gates.H(0))
circ.add(measurement)
circ.add(gates.CNOT(0,1))
circ.add(measurement2)

original_result = circ.execute(nshots=100)
print(original_result.frequencies())
print(measurement2.result.frequencies())

Expected to get the same result for measurement2.result.frequencies() as original_result.frequencies()
I Get the following error:
Traceback (most recent call last):
  File "/home/simonebordoni/QIBO/qibo/src/qibo/transpiler/test_m.py", line 23, in <module>
    print(measurement2.result.frequencies())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonebordoni/QIBO/qibo/src/qibo/measurements.py", line 189, in frequencies
    self.samples(binary=False)
  File "/home/simonebordoni/QIBO/qibo/src/qibo/measurements.py", line 167, in samples
    return self.backend.samples_to_decimal(self._samples, len(qubits))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonebordoni/QIBO/qibo/src/qibo/backends/numpy.py", line 639, in samples_to_decimal
    return self.np.matmul(samples, qrange)[:, 0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)
```

The error disappears if i remove the intermediate measurement gate. Everything also works fine if i try to recover the result of intermediate measurements:
```python
original_result = circ.execute(nshots=100)
print(original_result.frequencies())
print(measurement.result.frequencies())
```

**Comment by BrunoLiegiBastonLiegi** [comment]
This is addressed by #1109
