### ISSUE TITLE
Reuploading classifier expects states method from circuit result object

### ISSUE THREAD

**Issue by sorewachigauyo** [qiboteam/qibo#1286]
**Describe the bug**
The reuploading classifier example expects a `state()` method for the circuit result object on line 85 of `qclassifier.py`. This method exists for the `QuantumState` object which is a result of the numpy backend, but the qibolab backend returns a `MeasurementOutcomes` object which does not have said method.

**To Reproduce**
```
cd qibo/examples/reuploading_classifier
export QIBO_BACKEND="qibolab"
export QIBO_PLATFORM="dummy"
python3 main.py
```
On numpy
```
Problem solved before, obtaining parameters from file...
------------------------------------------------------------
[Qibo 0.2.5|INFO|2024-03-28 09:43:48]: Using numpy backend on /CPU:0
The value of the cost function achieved is 0.015078
The accuracy for this classification is 88.90 %
```
On qibolab
```
Problem solved before, obtaining parameters from file...
------------------------------------------------------------
[Qibo 0.2.5|INFO|2024-03-28 11:45:57]: Loading platform dummy
[Qibo 0.2.5|INFO|2024-03-28 11:45:57]: Using qibolab (dummy) backend on /CPU:0
[Qibo 0.2.5|ERROR|2024-03-28 11:45:57]: ry is not a native gate.
[Qibo 0.2.5|INFO|2024-03-28 11:45:57]: Connecting to instrument <qibolab.instruments.dummy.DummyInstrument object at 0x000002AADC03AE10>.
[Qibo 0.2.5|INFO|2024-03-28 11:45:57]: Connecting to dummy instrument.
[Qibo 0.2.5|INFO|2024-03-28 11:45:57]: Connecting to instrument <qibolab.instruments.dummy.DummyLocalOscillator object at 0x000002AADC049090>.
[Qibo 0.2.5|INFO|2024-03-28 11:45:57]: Minimal execution time (sequence): 0.0008
Traceback (most recent call last):
  File "C:\Users\pault\Documents\repos\qibo\examples\reuploading_classifier\main.py", line 53, in <module>
    main(**args)
  File "C:\Users\pault\Documents\repos\qibo\examples\reuploading_classifier\main.py", line 45, in main
    value_loss = ql.cost_function_fidelity()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pault\Documents\repos\qibo\examples\reuploading_classifier\qlassifier.py", line 104, in cost_function_fidelity
    cf += self.cost_function_one_point_fidelity(x, y)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pault\Documents\repos\qibo\examples\reuploading_classifier\qlassifier.py", line 85, in cost_function_one_point_fidelity
    state = C.execute().state()
            ^^^^^^^^^^^^^^^^^
```

**Comment by scarrazza** [comment]
@stavros11 besides this issue, could you please send to @sorewachigauyo our first notebook for quantum vqc regression, presented years ago to the TII team? Otherwise @MatteoRobbiati could you share the code used for the pdf fit? Thanks.

**Comment by MatteoRobbiati** [comment]
Thanks for opening this @sorewachigauyo.
The reuploading classifier, according to the algorithm introduced in the [original paper](https://arxiv.org/abs/1907.02085) needs the state representation to compute the loss function, which is a state fidelity indeed. 

If you consider a more hardware-friendly execution, e.g. shot-noise simulation or, indeed, execution on some quantum device, this strategy cannot be applied. In fact, what we can use to process information (at least without the gate set tomography) are only the frequencies we get after measurements. 

For this reason, in other works involving reuploading models (like the aforementioned regression), we defined a different optimization strategy, computing a Mean Squared Error loss function and using expectation values as predictors. 

An example of this approach can be found in a [recent code](https://github.com/qiboteam/rtqem/blob/b5c3eacf4e20afa6a0893fce657336d547cb9924/src/rtqem/vqregressor.py#L247) we implemented to compute real time quantum error mitigation during a VQA.
 
To give you a practical example:
In the case of a binary classification one can use a Pauli $Z$ as target observable and compute $$f = \langle 0 | U^{\dagger} Z U | 0\rangle,$$ where $U$ is your variational circuit.
Then classify the point as class A if $f\leq0.5$ or class B if $f<0.5$.

The expressibility of the model remains untouched, since you are only changing the way of processing the final information. 

In the end, I would say this error is well expected if the adopted strategy is the one implemented in the `qclassifier`.

**Comment by marekgluza** [comment]
@scarrazza: Paul managed to run via qibo the Gauss sum script and the results are reliable. 

We are now discussing the update from @MatteoRobbiati and @stavros11, thanks so much :)

**Comment by stavros11** [comment]
> @stavros11 besides this issue, could you please send to @sorewachigauyo our first notebook for quantum vqc regression, 

In case this is still helpful, I uploaded this notebook here: https://gist.github.com/stavros11/d737f45ef816911e1d40d0a0fd0fcce3
From a quick look it seems to only be using `Circuit`s so it should still work, despite all the changes that have been done in qibolab since that time (the only issue may be the transpiler/native gates). However, this notebook was just for a very first demo and the problem presented is quite simple, so the code shared by @MatteoRobbiati may be more useful.

**Comment by marekgluza** [comment]
Thanks @stavros11 and @MatteoRobbiati !

> In fact, what we can use to process information (at least without the gate set tomography) are only the frequencies we get after measurements.

The qubit state can be obtained as
$$\rho = \frac 12 (I + \langle X\rangle_\rho X+ \langle Y\rangle_\rho Y+ \langle Z\rangle_\rho Z$$ 
so the qibolab backend could have this as a simple (and noisy) way of returning the single qubit state

@mho291 are you planning to add such very simple procedures to test GST? If not, then @scarrazza we should plan to have more simple procedures in place for the 20q iqm chip?

**Comment by renatomello** [comment]
@MatteoRobbiati @scarrazza should this be transferred to `qiboml`?

**Comment by MatteoRobbiati** [comment]
I agree! We can move this there.
