### ISSUE TITLE
Auto Differentiation example bug

### ISSUE THREAD

**Issue by JoeGibbs88** [qiboteam/qibo#530]
I have tried to run the automatic differentiation example you provide in the documentation, and I encountered an error.

I ran the code:

```
import qibo
qibo.set_backend("tensorflow")
import tensorflow as tf
from qibo import gates, models

# Optimization parameters
nepochs = 1000
optimizer = tf.keras.optimizers.Adam()
target_state = tf.ones(4, dtype=tf.complex128) / 2.0

# Define circuit ansatz
params = tf.Variable(tf.random.uniform((2,), dtype=tf.float64))
c = models.Circuit(2)
c.add(gates.RX(0, params[0]))
c.add(gates.RY(1, params[1]))

for _ in range(nepochs):
    with tf.GradientTape() as tape:
        c.set_parameters(params)
        fidelity = tf.math.abs(tf.reduce_sum(tf.math.conj(target_state) * c()))
        loss = 1 - fidelity
    grads = tape.gradient(loss, params)
    optimizer.apply_gradients(zip([grads], [params]))
```

This produced the error message:

```
Traceback (most recent call last):
  File "first.py", line 23, in <module>
    optimizer.apply_gradients(zip([grads], [params]))
  File "/Users/joe/miniforge3/envs/qibo-env/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 598, in apply_gradients
    grads_and_vars = optimizer_utils.filter_empty_gradients(grads_and_vars)
  File "/Users/joe/miniforge3/envs/qibo-env/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/utils.py", line 78, in filter_empty_gradients
    raise ValueError("No gradients provided for any variable: %s." %
ValueError: No gradients provided for any variable: ['Variable:0'].
```

Can anyone see what needs to be modified? In its current form None is returned to grads

Thanks

**Comment by andrea-pasquale** [comment]
Thanks for spotting this.
```python
        c.set_parameters(params)
        final_state = c().state()
        fidelity = tf.math.abs(tf.reduce_sum(tf.math.conj(target_state) * final_state))
        loss = 1 - fidelity
```
The problem is that `c()`returns a qibo object which is the `VectorState` while in order to access the final state vector you need to call the `state` method as shown above.
In the next release we will fix this example in the documentation.

**Comment by JoeGibbs88** [comment]
Thanks!
