### ISSUE TITLE
readthedocs failing

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#830]
After introducing poetry, rtd is failing with:

```
Running Sphinx v1.8.6
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/qibo/envs/latest/lib/python3.8/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'nbsphinx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/qibo/envs/latest/lib/python3.8/site-packages/sphinx/cmd/build.py", line 300, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/qibo/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qibo/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qibo/envs/latest/lib/python3.8/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension nbsphinx (exception: No module named 'nbsphinx')

Extension error:
Could not import extension nbsphinx (exception: No module named 'nbsphinx')
```

because it doesn't install the docs dependencies:
```
WARNING: qibo 0.1.13.dev0 does not provide the extra 'docs'
```

Sounds like our toml is fully poetry centric (we do not define a `docs` parameter) therefore it fails.
If possible I would like to keep rtd for future releases until we have a complete centralized web page.
@AleCandido any suggestion?

**Comment by AleCandido** [comment]
Poetry has its own features, like dev dependencies (potentially grouped), and we are using that.
But of course it also supports `pip` features, like extras.

However, it is possible also to use Poetry features on rtd, through custom (documented) commands.

So, we have two options:
1. change the Poetry configuration, to add docs deps also as regular (but optional) deps, and gather them in the `docs` extras
2. or install the `docs` group with Poetry in rtd, as documented on the rtd docs https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry, by modifying the `.readthedocs.yaml` file

I believe that 2. would minimize the effort, since we'd have to maintain a single set of `docs` deps, and a single installation procedure.
But in the end both of the options are viable, and supposed to work :)

**Comment by scarrazza** [comment]
Thanks, option 2 works great!
